// Dialogue options for human-to-human collisions
export const humanCollisionDialogue = [
    "What a normal day to spend in a perfectly usual room.",
    "Nothing strange going on here at all.",
    "How's the weather outside? Quite normal, I imagine.",
    "Did you watch the game last night?",
    "This room seems completely ordinary to me.",
    "Have you noticed anything unusual? No? Me neither.",
    "I'm just having a perfectly ordinary day.",
    "Great party, isn't it? So... normal.",
    "I'm pretending not to notice anything unusual.",
    "Just another typical day in a typical room.",
    "Everything seems fine here, right?",
    "Let's talk about normal, human things.",
    "I don't see anything out of the ordinary, do you?",
    "Nice furniture in this room, very conventional.",
    "How about those sports teams?",
    "What a pleasant, ordinary gathering this is.",
    "Nothing to see here, just us humans talking.",
    "I'm enjoying this completely unremarkable event.",
    "Let's ignore any large mammals that may or may not be present.",
];

// Dialogue options for when humans are hit by objects
export const objectHitDialogue = [
    "I will continue to focus on enjoying this room despite these interruptions!",
    "The elephant in the room is... uh... just a metaphor, right?",
    "Did something just hit me? Must be the wind.",
    "Strange how things keep moving on their own...",
    "I'm sure there's a perfectly normal explanation for this.",
    "That vase just flew across the room? Haha, physics am I right?",
    "I'm going to pretend that didn't happen.",
    "That object just moved by itself? PERFECTLY NORMAL!",
    "I refuse to acknowledge anything unusual is happening.",
    "Must be a draft in here. A very strong, localized draft.",
    "Did you push that? No? Must have been my imagination.",
    "Let's all just agree that furniture is supposed to move sometimes.",
    "I'm just going to stand over here where it's safe... from the wind.",
    "Whoa! I mean... nothing happened. Nothing at all.",
    "I definitely don't see any large grey mammals flinging objects around.",
    "Is there a poltergeist in here or something?",
    "This is fine. Everything is fine.",
    "I will steadfastly deny any unusual occurrences.",
    "This is clearly some kind of practical joke.",
    "Let's continue our conversation as if nothing strange is happening.",
];